// <auto-generated />
using BookQuote.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace BookQuote.Api.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

        modelBuilder.Entity("BookQuote.Api.Models.Book", entity =>
        {
            entity.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");
            entity.Property<string>("Author")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("TEXT");
            entity.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            entity.Property<string>("Description")
                .HasMaxLength(2_000)
                .HasColumnType("TEXT");
            entity.Property<int?>("PublishedYear").HasColumnType("INTEGER");
            entity.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("TEXT");
            entity.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            entity.HasKey("Id");
            entity.ToTable("Books");
        });

        modelBuilder.Entity("BookQuote.Api.Models.Quote", entity =>
        {
            entity.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");
            entity.Property<string>("Author")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("TEXT");
            entity.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            entity.Property<string>("Source")
                .HasMaxLength(200)
                .HasColumnType("TEXT");
            entity.Property<string>("Text")
                .IsRequired()
                .HasMaxLength(4_000)
                .HasColumnType("TEXT");
            entity.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            entity.Property<int>("UserId").HasColumnType("INTEGER");
            entity.HasKey("Id");
            entity.HasIndex("UserId");
            entity.ToTable("Quotes");
        });

        modelBuilder.Entity("BookQuote.Api.Models.User", entity =>
        {
            entity.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");
            entity.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            entity.Property<string>("NormalizedUsername")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("TEXT");
            entity.Property<string>("PasswordHash")
                .IsRequired()
                .HasColumnType("TEXT");
            entity.Property<string>("Username")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("TEXT");
            entity.HasKey("Id");
            entity.HasIndex("NormalizedUsername").IsUnique();
            entity.ToTable("Users");
        });

        modelBuilder.Entity("BookQuote.Api.Models.Quote", entity =>
        {
            entity.HasOne("BookQuote.Api.Models.User", "User")
                .WithMany("Quotes")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            entity.Navigation("User");
        });

        modelBuilder.Entity("BookQuote.Api.Models.User", entity =>
        {
            entity.Navigation("Quotes");
        });
#pragma warning restore 612, 618
    }
}
