@host = http://localhost:5272
@token = paste-token-from-login-or-register-here
@bookId = 1
@quoteId = 1

### Health check
GET {{host}}/health

### Register - also creates five starter quotes
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "username": "pat",
  "password": "change-this-password"
}

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "pat",
  "password": "change-this-password"
}

### Current user
GET {{host}}/api/auth/me
Authorization: Bearer {{token}}

### List books
GET {{host}}/api/books
Authorization: Bearer {{token}}

### Create book
POST {{host}}/api/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "The Midnight Library",
  "author": "Matt Haig",
  "description": "A novel about choices and second chances.",
  "publishedYear": 2020
}

### Get book
GET {{host}}/api/books/{{bookId}}
Authorization: Bearer {{token}}

### Update book
PUT {{host}}/api/books/{{bookId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "The Midnight Library",
  "author": "Matt Haig",
  "description": "Updated description.",
  "publishedYear": 2020
}

### Delete book
DELETE {{host}}/api/books/{{bookId}}
Authorization: Bearer {{token}}

### List the signed-in user's quotes
GET {{host}}/api/quotes
Authorization: Bearer {{token}}

### Create quote
POST {{host}}/api/quotes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "The only way to learn is to live.",
  "author": "Matt Haig",
  "source": "The Midnight Library"
}

### Get quote
GET {{host}}/api/quotes/{{quoteId}}
Authorization: Bearer {{token}}

### Update quote
PUT {{host}}/api/quotes/{{quoteId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "The only way to learn is to live.",
  "author": "Matt Haig",
  "source": "The Midnight Library"
}

### Delete quote
DELETE {{host}}/api/quotes/{{quoteId}}
Authorization: Bearer {{token}}
